### ISSUE TITLE
Cannot find /home/user/emsdk/upstream/bin/lli 

### ISSUE THREAD

**Issue by ghost** [blacktm/ruby-wasm#8]
When I try and build a simple hello-world program, this comes up:

```shell
/var/lib/gems/2.5.0/gems/wasm-0.0.2/bin/ruby-wasm:40: warning: Insecure world writable dir /usr in PATH, mode 040777
WARNING  root: (Emscripten: settings file has changed, clearing cache)
WARNING  root: LLVM version appears incorrect (seeing "(/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project", expected "3.4")
INFO     root: (Emscripten: Running sanity checks)
CRITICAL root: Cannot find /home/stencylxd/emsdk/upstream/bin/lli, check the paths in ~/.emscripten
```
Gem Version: 0.02
Emscripten is installed.
I'm on x86_64 with Ubuntu (latest)
WebAssembly is installed. (toolchain) 

I followed the blog post tutorial. Is that outdated?
@blacktm

**Comment by ghost** [comment]
Error was fixed when I reinstalled Emscripten.

**Comment by iocmet** [comment]
how to reinstall? i have same error i installed emscripten from api but i get this error on compiling project

dos_programs.cpp:28:10: fatal error: 'emscripten/fetch.h' file not found
#include <emscripten/fetch.h>

and i install emscripten with https://emscripten.org/docs/getting_started/downloads.html
but now i get error
Cannot find /home/ubuntu/github/emsdk/upstream/bin/llvm-as, check the paths in /home/ubuntu/github/emsdk/.emscripten
